language: node_js
node_js:
- '12'
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  target_branch: master
  on:
    branch: master复制代码
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean && hexo g -d
cache:
  directories:
  - node_modules
